### ISSUE TITLE
NodeJS/Webpack broken

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-webseite#268]
I tried to run the current master on Archlinux.

Something is not working :-1: 

https://asciinema.org/a/7B7ob9BxmDakv63HU3Ml9Qhue

```bash
 master $ make build
lektor clean --yes
Started clean
Finished clean in 0.01 sec
lektor build -f webpack
Started build
Running yarn install
node: error while loading shared libraries: libicui18n.so.64: cannot open shared object file: No such file or directory
Starting webpack build
Finished build in 0.00 sec
Traceback (most recent call last):
  File "/usr/bin/lektor", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/lektor/cli.py", line 627, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lektor/cli.py", line 237, in build_cmd
    success = _build()
  File "/usr/lib/python3.7/site-packages/lektor/cli.py", line 230, in _build
    failures = builder.build_all()
  File "/usr/lib/python3.7/site-packages/lektor/builder.py", line 1137, in build_all
    self.env.plugin_controller.emit('before-build-all', builder=self)
  File "/usr/lib/python3.7/site-packages/lektor/pluginsystem.py", line 161, in emit
    rv[plugin.id] = handler(**kwargs)
  File "/home/l3d/.cache/lektor/packages/439cea7b17ed9be0614438d01d2c87e9/lektor_webpack_support.py", line 61, in on_before_build_all
    self.run_webpack().wait()
  File "/home/l3d/.cache/lektor/packages/439cea7b17ed9be0614438d01d2c87e9/lektor_webpack_support.py", line 24, in run_webpack
    return portable_popen(args, cwd=webpack_root)
  File "/usr/lib/python3.7/site-packages/lektor/utils.py", line 491, in portable_popen
    raise RuntimeError('Could not locate executable "%s"' % cmd[0])
RuntimeError: Could not locate executable "/home/l3d/git/toolbox-webseite/webpack/node_modules/.bin/webpack"
make: *** [Makefile:25: build] Fehler 1
```

**Comment by DO1JLR** [comment]
**Überraschung:**

NodeJS ist unerwarteterweise etwas kaputt unter Linux:

```bash
node --version
node: error while loading shared libraries: libicui18n.so.64: cannot open shared object file: No such file or directory
```

Bin dafür den #265 wieder zu reverten und durch etwas funktionierendes zu ersetzen.
Oder es braucht ein besseres Makefile!

**Comment by maxbachmann** [comment]
hattest du das denn nicht getestet?

**Comment by maxbachmann** [comment]
Installier mal ```icu``` und teste es dann nochmal.

**Comment by DO1JLR** [comment]
> hattest du das denn nicht getestet?

Doch, damals ware nodejs aber noch nicht kaputt mit seiner version

**Comment by DO1JLR** [comment]
Update:

Dieses nodejs braucht wohl ein komplettupdate vom System (oder von einigen komponmenten) damit es überhaupt funktioniert.

So ein dreck!

icu war bereits installiert.

Ein Update der folgenden Packete auf die aktuelle Version hat geholfen:

```bash
 master $ sudo pacman -Syu
:: Synchronisiere Paketdatenbanken...
 core ist aktuell
 extra ist aktuell
 community ist aktuell
 multilib ist aktuell
:: Starte vollständige Systemaktualisierung...
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (52) akonadi-18.12.3-5  akonadi-contacts-18.12.3-2  bbswitch-0.8-209  bind-tools-9.13.7-2  boost-libs-1.69.0-2  brltty-6.0-2  cups-filters-1.22.4-1  epiphany-3.32.1.2-2
            evolution-data-server-3.32.0-2  ghostscript-9.27-1  glslang-7.11.3113-1  gnome-weather-3.32.1-1  harfbuzz-2.4.0-2  harfbuzz-icu-2.4.0-2  icu-64.1-1  jbig2dec-0.16-1
            lib32-harfbuzz-2.4.0-2  lib32-icu-64.1-1  lib32-libtiff4-3.9.7-4  lib32-libxml2-2.9.9-2  libakonadi-18.12.3-5  libcdr-0.1.5-2  libcroco-0.6.13-1  libe-book-0.1.3-5  libical-3.0.4-3
            libmspub-0.1.4-5  libnotify-0.7.8-1  libphonenumber-8.10.6-2  libqalculate-3.0.0-2  libqxp-0.0.2-2  libreoffice-fresh-6.2.2-3  libsynctex-2018.48691-8  libtiff4-3.9.7-4
            libvisio-0.1.6-6  libxml2-2.9.9-2  libzmf-0.0.2-6  linux-5.0.6.arch1-1  nvidia-418.56-6  oath-toolkit-2.6.2-6  qt4-4.8.7-28  qt5-base-5.12.2-2  qt5-location-5.12.2-2
            qt5-webengine-5.12.2-2  qt5-webkit-5.212.0alpha2-26  raptor-2.0.15-11  texlive-bin-2018.48691-8  thunderbird-60.6.1-2  tracker-2.2.1-2  tracker-miners-2.2.1-2  webkit2gtk-2.24.0-2
            xfsprogs-4.20.0-2  xmlsec-1.2.27-2
```
