### ISSUE TITLE
Lektor broken

### ISSUE THREAD

**Issue by haekelhexe** [ToolboxBodensee/toolbox-webseite#419]
When trying to work on the website with Lektor on Xubuntu, I recently get the following: 

maren@maren-Aspire-E3-111:~/toolbox-webseite$ lektor server
Traceback (most recent call last):
  File "/home/maren/.local/bin/lektor", line 10, in <module>
    sys.exit(main())
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 627, in main
    cli.main(args=args, prog_name=name)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 380, in server_cmd
    ctx.load_plugins()
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 131, in load_plugins
    initialize_plugins(self.get_env())
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/lektor/pluginsystem.py", line 122, in initialize_plugins
    plugins = load_plugins()
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/lektor/pluginsystem.py", line 116, in load_plugins
    rv[ep.name] = ep.load()
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/maren/.local/lib/lektor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/maren/.cache/lektor/packages/aedf320c194fc45d894500d632d99726/lektor_scsscompile.py", line 30
    def is_enabled(self, build_flags) -> bool:
                                      ^
SyntaxError: invalid syntax

**Comment by maxbachmann** [comment]
Ich sollte das vor 16 Tagen gefixt haben, leider hat Alex das dann nicht mehr getestet und ich hätte das gern getestet, ob das das Problem behebt.
Kannst du mal aus der Datei toolbox-webseite.lektorproject die Zeilen
```
lektor-jsminify = 1.4		
lektor-scsscompile = 1.2.3
```
entfernen und dann
```
git clone https://github.com/maxbachmann/lektor-JSminify.git packages/lektor-JSminify
git clone https://github.com/maxbachmann/lektor-SCSScompile.git packages/lektor-SCSScompile
```
ausführen um die hoffentlich gefixte version direkt zu in das package Verzeichnis zu laden

Anschließend sollte
```
lektor server
```
wieder funktionieren. Bitte um Rückmeldung ob es dann funktioniert :)
